---
environment: ose_disconn2
cluster_id: "{{ environment }}"
create_vpcs: true
vpc_public_id: vpc-1234abcd  # used if create_vpcs=false
vpc_private_id: vpc-5678defg # used if create_vpcs=false
r53_zone: "rhtps.io"
ec2_keypair: ose_disconn
#ec2_instance_count: 5
ec2_region: us-east-1
ec2_username: ec2-user
ec2_region_sidea: "{{ ec2_region }}a"
ec2_region_sideb: "{{ ec2_region }}e"
ec2_image: ami-2051294a
ec2_instance_type: m4.xlarge
vncuser: osedisconn
vncpass: Os3disc0nn
domain: openshift.internal
apps_domain: "apps.{{ domain }}"
forwarders:
  - 8.8.8.8
  - 8.8.4.4
a_records:
  - host: "*.{{ apps_domain }}"
    ip: 192.168.1.5